# Generated by Django 3.2.5 on 2021-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_post_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_one',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_two',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
