# Generated by Django 3.2.5 on 2021-07-30 00:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blurb',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
